In [42]:
import torch
from torch import tensor
import numpy as np

In [24]:
def matmul1(a,b):
  ar,ac = a.shape
  br,bc = b.shape
  assert ac == br
  c = torch.zeros(ar,bc)
  for i in range(ar):
    for k in range(bc):
      for j in range(ac): c[i,k] += a[i,j]*b[j,k] 
  return c


In [16]:
f = torch.randn(3,2)
fr, fc = f.shape
print(fr,fc)
f

3 2


tensor([[-0.0085,  0.7291],
        [ 0.1331,  0.8640],
        [-1.0157, -0.8887]])

In [21]:
f2 = torch.randn(2,1)
f2

tensor([[ 0.4679],
        [-0.2049]])

In [25]:
matmul(f,f2)

tensor([[-0.1534],
        [-0.1148],
        [-0.2931]])

In [26]:
f@f2

tensor([[-0.1534],
        [-0.1148],
        [-0.2931]])

In [13]:
m1 = torch.randn(5, 784).cuda()
m2 = torch.randn(784, 10).cuda()

In [28]:
%time matmul(m1,m2)

CPU times: user 729 ms, sys: 0 ns, total: 729 ms
Wall time: 737 ms


tensor([[ 20.4556,  16.3589,  17.3697,  10.7952,  -5.0137,  15.8283,  -0.6433,   1.0742,  42.7838, -13.4226],
        [ 17.1288,  25.3569,   6.5654, -27.3038, -17.2624,  21.4736,   7.7040,  21.0932,  -7.9843, -58.4536],
        [ 18.7078,  -0.7761,  -2.4135,  17.6966, -34.7733, -10.1749,  -9.4549, -14.4562,   0.1597,  45.6993],
        [-45.6807,  30.2635, -36.4334,  -4.7199,  19.3923, -21.0885,   5.3866, -38.4594,  11.5221,  13.2045],
        [-17.2932,  -6.3994,  20.5691,  18.7861,  -8.2135,  -1.9999, -30.6286, -26.2472, -34.4538,   2.9838]])

In [14]:
%time m4 = m1@m2.cuda()

CPU times: user 867 µs, sys: 0 ns, total: 867 µs
Wall time: 643 µs


In [33]:
def matmul2(a,b):
  ar,ac = a.shape
  br,bc = b.shape
  assert ac == br
  c = torch.zeros(ar,bc)
  for i in range(ar):
    for k in range(bc):
      c[i,k] = (a[i,:]*b[:,k]).sum() 
  return c

In [34]:
%time matmul2(m1,m2)

CPU times: user 4.11 ms, sys: 0 ns, total: 4.11 ms
Wall time: 7.97 ms


tensor([[ 20.4556,  16.3589,  17.3697,  10.7952,  -5.0137,  15.8283,  -0.6433,   1.0742,  42.7838, -13.4226],
        [ 17.1288,  25.3569,   6.5654, -27.3038, -17.2624,  21.4736,   7.7040,  21.0932,  -7.9843, -58.4536],
        [ 18.7078,  -0.7761,  -2.4135,  17.6966, -34.7733, -10.1749,  -9.4549, -14.4562,   0.1597,  45.6993],
        [-45.6807,  30.2635, -36.4335,  -4.7199,  19.3923, -21.0885,   5.3866, -38.4594,  11.5221,  13.2045],
        [-17.2932,  -6.3994,  20.5691,  18.7861,  -8.2134,  -1.9999, -30.6286, -26.2472, -34.4538,   2.9838]])

In [39]:
m3-5

tensor([[ 15.4556,  11.3589,  12.3697,   5.7952, -10.0137,  10.8283,  -5.6433,  -3.9258,  37.7838, -18.4226],
        [ 12.1289,  20.3569,   1.5654, -32.3037, -22.2624,  16.4735,   2.7040,  16.0932, -12.9843, -63.4536],
        [ 13.7078,  -5.7761,  -7.4135,  12.6966, -39.7733, -15.1749, -14.4549, -19.4562,  -4.8403,  40.6993],
        [-50.6807,  25.2635, -41.4335,  -9.7199,  14.3923, -26.0885,   0.3866, -43.4595,   6.5221,   8.2045],
        [-22.2932, -11.3994,  15.5691,  13.7861, -13.2134,  -6.9999, -35.6286, -31.2472, -39.4538,  -2.0162]])

In [60]:
f3 = tensor([[10.,20.,30.], []])

ValueError: ignored

In [53]:
f3.shape

torch.Size([2, 3])

In [59]:
f3.squeeze(-1)
f3.shape

torch.Size([2, 3])

In [55]:
f3

tensor([[10., 20., 30.],
        [ 1.,  2.,  3.]])

In [61]:
def matmul3(a,b):
  ar,ac = a.shape
  br,bc = b.shape
  assert ac == br
  c = torch.zeros(ar,bc)
  for i in range(ar):
      c[i] = (a[i].unsqueeze(-1)*b).sum() 
  return c

In [62]:
%time matmul3(m1,m2)

CPU times: user 2.28 ms, sys: 0 ns, total: 2.28 ms
Wall time: 5.4 ms


tensor([[105.5860, 105.5860, 105.5860, 105.5860, 105.5860, 105.5860, 105.5860, 105.5860, 105.5860, 105.5860],
        [-11.6822, -11.6822, -11.6822, -11.6822, -11.6822, -11.6822, -11.6822, -11.6822, -11.6822, -11.6822],
        [ 10.2146,  10.2146,  10.2146,  10.2146,  10.2146,  10.2146,  10.2146,  10.2146,  10.2146,  10.2146],
        [-66.6131, -66.6131, -66.6131, -66.6131, -66.6131, -66.6131, -66.6131, -66.6131, -66.6131, -66.6131],
        [-82.8966, -82.8966, -82.8966, -82.8966, -82.8966, -82.8966, -82.8966, -82.8966, -82.8966, -82.8966]])

In [31]:
def lin(x,w,b): return x@w + b

In [78]:
x = torch.randn(100,100)

In [70]:
x

tensor([[-1.6253,  0.7517, -0.5054,  ..., -0.1512,  0.1547,  0.4189],
        [-1.9801,  1.8460, -0.1609,  ...,  0.2059, -0.2049, -0.4009],
        [ 1.7347,  0.3049,  0.6474,  ..., -0.9877,  1.8186, -0.1373],
        ...,
        [-1.9551, -0.3037, -0.0805,  ...,  0.0955,  1.0041,  1.2910],
        [-1.6071, -2.0280,  0.7420,  ...,  0.9374, -0.5417, -0.2643],
        [-2.4074, -0.5886,  0.5691,  ..., -0.2283, -0.2786, -1.5140]])

In [28]:
w1 = torch.randn(100,50)
b1 = torch.randn(50)
w2 = torch.randn(50,1)
b2 = torch.randn(1)

In [35]:
lin1 = lin(x,w1,b1)

In [36]:
lin1.shape

torch.Size([200, 50])

In [79]:
x.mean(), x.std()

(tensor(-0.0054), tensor(1.0036))

In [93]:
x = torch.randn(100,100)
print(x.mean(), x.std())
for i in range(50): x = x@(torch.randn(100,100)*0.1)

tensor(0.0306) tensor(0.9988)


In [94]:
x

tensor([[-0.5825,  1.5587,  0.3413,  ...,  1.7212,  0.3532, -0.5376],
        [ 0.3641, -0.9382,  0.3659,  ..., -0.8807, -0.8085, -0.0111],
        [ 0.2866, -2.2930, -0.7623,  ..., -0.2191,  0.5159, -1.5525],
        ...,
        [-0.0979,  0.9209,  0.0121,  ...,  0.0768,  0.4441,  0.5471],
        [ 0.4082, -0.5461, -0.2776,  ..., -0.9830,  0.6760, -0.0637],
        [ 0.0653,  0.1561,  0.2008,  ...,  0.6258,  0.2659, -0.2576]])